/**
 * عن المشروع — the About page content, written by a specialist-writer + reviewer
 * pipeline (see docs). Rendered by views/About.tsx. Prose uses \n\n paragraphs,
 * **bold**, and "- " bullet lines.
 */
export interface AboutSection { id: string; ar_heading: string; en_heading: string; ar_body: string; en_body: string; }
export const ABOUT_SECTIONS: AboutSection[] = [
  {
    "id": "mishkat-research",
    "ar_heading": "مشروعٌ بحثيٌّ في القرآن يستفيدُ من الذكاء الاصطناعيّ",
    "en_heading": "A Qur'anic research project that draws on artificial intelligence",
    "ar_body": "«مشكاة» مشروعٌ بحثيٌّ رياضيٌّ يستخدمُ الذكاءَ الاصطناعيّ في النظرِ إلى القرآن: نبني «رسمًا معرفيًّا محسوبًا» من نصّ المصحف، لنُبرِزَ ترابُطَ الكتاب ونظمَه — كيف تتناسبُ آياتُه، وتتشابكُ جذورُه ومعانيه في نسيجٍ واحد.\n\nمنهجُنا حسابٌ ثمّ عرض: نستخرجُ من نصّ القرآن علاقاتِ الألفاظ والمعاني بالحساب، ونعرضُها مادّةً بين يدَي القارئ تُعينُه على التدبّرِ والبحث.",
    "en_body": "Mishkāt is a mathematical research project that uses artificial intelligence to look into the Qur'an: we build a *computed knowledge graph* from the muṣḥaf's text, to bring out the Book's coherence and order — how its verses answer one another and its roots and meanings interlace into a single fabric.\n\nOur method is compute, then present: from the Qur'anic text we extract computed relations between words and meanings, and present them as material in the reader's hands, aiding reflection and study."
  },
  {
    "id": "embeddings-vectors",
    "ar_heading": "كيف يقيسُ الحاسوبُ قُربَ المعنى؟ — التضميناتُ والمتّجهاتُ وجيبُ التمام",
    "en_heading": "How the machine measures closeness of meaning — embeddings, vectors, and cosine",
    "ar_body": "قلبُ المشروع حسابٌ لا رأي. لكنْ كيف «يقيسُ» جهازٌ معنى آية؟ الجوابُ في ثلاث خطواتٍ يقومُ عليها كلُّ ما نبنيه.\n\n**١. من المعنى إلى الأرقام — التضمين (embedding).** نُمرِّرُ كلَّ آيةٍ على نموذجٍ لغويٍّ ضخم (نموذج Gemini)، فيُحوّلُ معناها إلى سلسلةٍ من ٧٦٨ رقمًا تُسمَّى «المتَّجِه» (vector). فتصيرُ كلُّ آيةٍ نقطةً في «فضاءٍ للمعنى» ذي ٧٦٨ بُعدًا: النقاطُ المتقاربةُ فيه آياتٌ متقاربةُ المعنى، والمتباعدةُ متباعدتُه — بالمعنى لا باللفظ (فـ«أنفقوا» و«تصدَّقوا» متجاورتان وإن اختلفَ حرفُهما).\n\n**٢. قياسُ القرب — جيبُ التمام (cosine).** نقيسُ قُربَ آيتين بالزاويةِ بين متَّجهيهما: كلّما صغُرت الزاويةُ اشتدَّ تقاربُ المعنى — رقمٌ بين صفرٍ وواحد. هذا حسابٌ هندسيٌّ محضٌ، يُعادُ فيُعطي النتيجةَ نفسَها في كلِّ مرّة، لا يدخلُه رأيٌ ولا مِزاجٌ ولا تأويل.\n\n**٣. ماذا نبني على ذلك.** من هاتين اللبِنتين تنبثقُ أدواتٌ عِدّة:\n\n- **المركز (centroid):** متوسّطُ متَّجهاتِ مجموعةِ آياتٍ يُمثّلُ معناها الجامع. به رسَونا «مرساةَ التوحيد» (مركزَ آيات «لا إله إلا الله»)، وبه نتتبّعُ أيَّ معنًى عبر المصحف.\n- **التجميع (k-means):** نجمعُ الآياتِ في تسعينَ محورًا بحسبِ تجاورِها في الفضاء، ثمّ يُسمَّى كلُّ محورٍ بموضوعه.\n- **أقربُ الجيران:** نحفظُ لكلِّ آيةٍ أقربَ جيرانها معنًى عبر المصحف كلِّه، فعليها يقومُ «مثلها» والبحثُ الدلاليّ.\n\nوالنموذجُ يقيسُ قُربَ المعنى فحسب.",
    "en_body": "The heart of the project is computation, not opinion. But how does a machine *measure* a verse's meaning? In three steps that everything here rests on.\n\n**1. From meaning to numbers — the embedding.** Each verse is passed through a large language model (Gemini), which turns its meaning into a list of 768 numbers — a *vector*. Every verse becomes a point in a 768-dimensional *meaning space*: nearby points are verses near in meaning, distant points distant in meaning — by meaning, not wording (so \"anfiqū\" and \"taṣaddaqū\" sit close though their letters differ).\n\n**2. Measuring closeness — cosine.** We gauge the closeness of two verses by the angle between their vectors: the smaller the angle, the closer the meaning — a number from 0 to 1. Pure geometry, giving the same result every run — no opinion, no mood, no interpretation enters it.\n\n**3. What we build on it.** From these two building blocks several instruments emerge:\n\n- **The centroid:** the average of a set of vectors represents their shared meaning. It anchors *tawḥīd* (the centre of the \"lā ilāha illā-llāh\" verses) and lets us trace any concept across the muṣḥaf.\n- **Clustering (k-means):** verses group into ninety themes by their proximity in the space, and each theme is then named by its subject.\n- **Nearest neighbours:** for every verse we keep its closest verses in meaning across the whole muṣḥaf, and on these «similar verses» and semantic search are built.\n\nThe model measures closeness of meaning — nothing more."
  },
  {
    "id": "jamiiyya-mizan",
    "ar_heading": "الدليلُ المحسوب: بواباتُ القاعدة وشبكةُ التفرُّع",
    "en_heading": "Computed evidence: rule-gates and the elaboration network",
    "ar_body": "هذا قلبُ المشروع، وقد بُني على مبدأٍ واحد: **الادّعاءُ على قدرِ الدليل.** لا نمنحُ الآيةَ «درجةَ أهمّيّة» من معادلةٍ — جرّبنا ذلك وتركناه (قصّتُه كاملةً في «كيف تطوّر الميزان» أدناه) — بل نعرضُ لكلِّ آيةٍ ما **ثبت** لها حسابًا، شارتين لا رتبة:\n\n\n\n**الشارةُ الأولى — «صيغةُ قاعدة».** بواباتُ عمومٍ حتميّةٌ من صرف القرآن (مدوّنة QAC): الحصرُ («إنما»، «ما… إلا»)، وشرطُ العموم («مَن يعمل…»)، والنفيُ المستغرِق («لا إكراهَ»)، وأفعالُ التشريع الثمانية المسندةُ إلى الله («كتب، حرّم، أحلّ…» — قائمةٌ مغلقةٌ معلنة)، والأمرُ العامّ، والموصولُ العامّ، وغيرُها — كلُّ بوابةٍ نعم/لا، تُعرَضُ بأسمائها تحت الآية. والوحدةُ **المقطعُ** لا الآيةُ وحدَها: فقاعدةُ ﴿اليومَ أكملتُ لكم دينكم﴾ تُرى وإن سكنت آيةً طويلة. وحواجبُ سردٍ تمنعُ آياتِ الوقائع (أُختبرت البواباتُ على عيّنةِ إجماعٍ مجمَّدةٍ من التراث: استعادت ستًّا وتسعين بالمئة من قواعد الإجماع في عيّنة الضبط، ورفضت آياتِ الوقائع السردية رفضًا شبه تامّ — والإخفاقاتُ القليلة موثّقةٌ بأسبابها في تقرير التحقّق المنشور).\n\n\n\n**الشارةُ الثانية — «ثبت تفرُّعُه».** شبكةُ علاقاتٍ موجَّهة: عُرض أكثرُ من مئةِ ألف زوجٍ من الآيات على حاكمٍ آليٍّ محايدٍ **لا يرى حكمَ غيره**، يسألُ سؤالَ الحذف: لو حُذفت هذه لبقيت تلك قائمةً؟ ولو حُذفت تلك لفقدت هذه أصلَها؟ فإن صدق الشرطان سمّى العلاقة: **بيانٌ** أو **مثالٌ** أو **جزاءٌ** أو **توكيد** — وإلا فلا رابط. نجا من هذا الامتحان ١١٬٧٧٣ رابطًا فقط (من كل مئةِ زوجٍ يثبتُ أحدَ عشرَ) — فما تراه في بطاقة الآية من «بيانِها وأمثالِها وجزائِها» روابطُ ناجيةٌ من امتحانٍ صارم، لا تشابهٌ خام. ومعها **المثاني**: مواضعُ تُعيدُ صياغةَ المعنى نفسِه، محسوبةً بتطابق تسلسل الكلم.\n\n\n\n**لماذا شارتان ولا رتبة؟** لأنّ الصدقَ يقتضيه: البواباتُ تُثبت أنّ الآيةَ *مصوغةٌ صياغةَ قاعدة*، والشبكةُ تُثبت أنّ غيرَها *يتفرّع عنها فعلًا* — وهذان دليلان مختلفان يُعرَضان باسمَيهما. أمّا رتبةٌ واحدةٌ شاملة («هذه أعظمُ من تلك») فقد بيّن التحقّقُ أنّ عمقَ الشبكة الحاليَّ لا يحملها بأمانة — فلم ندّعِها. إن تعمّقت الشبكةُ يومًا وحملتها، أضفناها بالدليل.\n\n\n\n**إعادةُ الإنتاج كاملة.** نصوصُ التعليمات الحرفيّةُ للحاكم، ودفعاتُ المرشّحين كما رآها، وكلُّ حكمٍ خامٍ (بما فيه المرفوض)، واتفاقُ الحاكمَين المستقلَّين (κ)، وتقريرُ التحقّق بإخفاقاته قبل نجاحاته — كلُّها منشورةٌ في مستودع المشروع. **الذكاءُ يحكم على أصغرِ وحدةٍ قابلةٍ للطعن (زوجُ آيتين وعلاقة)، والحسابُ يجمع، والقارئُ يفتّش.**",
    "en_body": "This is the project's heart, built on one principle: **claim only what the evidence carries.** We do not assign verses an 'importance score' from a formula — we tried that and retired it (the full story is in 'How the measure evolved') — instead, every verse shows what has been **established** for it computationally: two badges, no rank:\n\n\n\n**Badge one — 'Rule form.'** Deterministic generality gates from the Qur'an's morphology (QAC): restriction (innamā, mā…illā), universal conditionals, exhaustive negation, the eight legislative verbs ascribed to God (a closed published list), general imperatives, the generic relative — each gate a yes/no, shown by name under the verse. The unit is the **clause**, not just the whole verse. Narrative blockers keep event-verses out (validated on a frozen consensus sample: 96% recall of consensus rules on the tuning half, near-total rejection of narrative — the few failures documented with their causes in the published validation report).\n\n\n\n**Badge two — 'Proven elaboration.'** A directed network: over one hundred thousand verse-pairs were put to a blind judge that sees no one else's verdict and applies the deletion test — if this were removed, would that still stand? if that were removed, would this lose its basis? Only when both hold does it name the relation: **bayān**, **mithāl**, **jazāʾ**, or **tawkīd** — 11,773 links survived (about 11 in every 100). What you see on a verse's card are links that survived a hard exam, not raw similarity. Alongside them, the **mathānī**: places restating the same meaning, computed by word-sequence identity.\n\n\n\n**Why two badges and no rank?** Honesty requires it: gates prove a verse is *phrased as a rule*; the network proves others *actually branch from it* — two different kinds of evidence, shown under their own names. A single global rank ('this outweighs that') is not carried faithfully by the network's current depth — so we do not claim it. Should the network deepen enough to carry it, we will add it with evidence.\n\n\n\n**Full reproducibility.** The judge's verbatim instructions, the exact candidate batches, every raw verdict (including rejections), the two independent judges' agreement (κ), and the validation report with its failures before its successes — all published in the project's repository. **AI judges the smallest contestable unit (a pair and a relation); computation aggregates; the reader audits.**",
  },
  {
    "id": "mizan-story",
    "ar_heading": "كيف تطوّر الميزان — ثلاثة أجيال",
    "en_heading": "How the measure evolved — three generations",
    "ar_body": "لم يولد هذا الدليلُ ناضجًا؛ مرّ بثلاثة أجيالٍ نحفظ قصّتَها كاملةً لأنّ الأمانةَ العلمية تقتضي حفظَ الطريق لا آخرِه فقط.\n\n**الجيل الأول** كان لجنةَ قراءةٍ آلية: أسرابٌ من النماذج صنّفت الآيات وربطت التفصيلَ بأصوله ثم راجعها سربٌ ناقد. خرجت منه شبكةٌ نافعة، لكنّ مراجعتَه لم تكن عمياءَ تمامًا، وسجلّاتُه بقيت خارج المستودع.\n\n**الجيل الثاني** أراد الحتميّةَ الكاملة: معادلةٌ من ستة عواملَ موزونةٍ تمنح كلَّ آيةٍ «درجةَ جامعية». كانت قابلةً لإعادة الإنتاج فعلًا — لكنّ مراجعةً نقديّةً مستقلّة أثبتت أنّ شكلَ الدالّة نفسَه يقيس القربَ من صيغةٍ بعينها لا حقيقةَ الجامعية، وأنّ آياتٍ أطبق العلماءُ على جامعيّتها نزلت ظلمًا. فأوقفناه.\n\n**الجيل الثالث** — المعروضُ اليوم — بُني على عيّنةِ إجماعٍ جُمِّدت قبل أيّ ضبط، وبواباتٍ صرفيةٍ حتمية، وشبكةِ حكمٍ أعمى، وتقريرِ تحقّقٍ نُشر بإخفاقاته قبل نجاحاته. وحين تبيّن أنّ عمقَ الشبكة لا يحمل رتبةً شاملةً بأمانة، اخترنا شارتَي الدليل ولم ندّعِ الرتبة.\n\nالقصةُ كاملةً — بأرقام كلِّ جيلٍ وعيوبِه المثبتة وأسبابِ العدول — منشورةٌ في مستودع المشروع (STORY-OF-THE-MIZAN).",
    "en_body": "This evidence system was not born mature; it passed through three generations, and we preserve the whole story because scientific honesty means keeping the road, not just its end.\n\n**Generation one** was a machine reading-committee: model swarms classified verses and attached details to their principles, then a skeptical swarm reviewed. A useful network emerged — but its review was not fully blind, and its records lived outside the repository.\n\n**Generation two** sought full determinism: a six-factor weighted formula scoring each verse's jāmiʿiyya. Genuinely reproducible — but an independent critical review proved the function's very shape measured nearness to a particular phrasing rather than true foundationality, unjustly demoting verses whose foundational status scholars agree on. We retired it.\n\n**Generation three** — what you see today — was built on a consensus sample frozen before any tuning, deterministic morphological gates, a blind-judged network, and a validation report published with its failures before its successes. And when it became clear the network's current depth cannot honestly carry a single global rank, we chose the two evidence badges and claimed no rank.\n\nThe full story — each generation's numbers, proven flaws, and reasons for change — is published in the project repository (STORY-OF-THE-MIZAN)."
  },
  {
    "id": "sections-on-mizan",
    "ar_heading": "جولةٌ في الأقسام: ما بُنِيَ على الميزان",
    "en_heading": "A tour of the sections: what is built on the measure",
    "ar_body": "من الميزان والمتّجهات تتفرّعُ الأقسامُ الآتية، كلٌّ يعملُ بطريقةٍ معلومة:\n\n**الكلّيّات (/kulliyat).** تصنيفُ كلّ آية: مرتبتُها، ومحورُها، ومؤشّرُها؛ ولوحةُ «لماذا هذه المرتبة؟» تُظهرُ حسابَ العوامل الستّة عِيانًا. تُعرَضُ بترتيب المصحف أو بترتيب الجامعيّة (الأصلُ أوّلًا).\n\n**خريطةُ المصحف (/shabaka).** كلُّ آيةٍ خليّةٌ ملوّنةٌ بمرتبتها المحسوبة — كلّيّةً أو جامعةً أو تفصيلًا — مصفوفةً بترتيب المصحف وسورِه؛ فتُرى في نظرةٍ واحدةٍ أين تقعُ الأصولُ الجامعةُ عبر القرآن كلِّه: هيكلُ الكتابِ كما يرسمُه الميزان.\n\n**الخيوطُ الموضوعيّة (/khayt).** تتبُّعُ أيِّ معنًى عبر المصحف: نبدأُ بتأصيلٍ لفظيٍّ دقيق (مواضعُ اللفظ ومواضعُ جذرِه) نواةً صُلبة، ثمّ نضيفُ هالةً دلاليّةً ضيّقةً من أقرب الآيات معنًى، مع بصمةِ حضورِ الخيط عبر السور الأربع عشرة بعد المئة. (وقد آثرنا التأصيلَ اللفظيَّ لأنّ القربَ الدلاليَّ وحده فضفاضٌ في الألفاظ الخاصّة.)\n\n**المواضيع (/mawdui).** موضوعاتُ القرآن كما تنشأُ حسابيًّا: تسعونَ محورًا تُجمَعُ إليها الآياتُ بتقاربِ المعنى فتُغطّي المصحفَ كلَّه، كلُّ آيةٍ في محورٍ واحد، وآياتُ كلِّ محورٍ مرتّبةٌ بالجامعيّة (الأصلُ أوّلًا). طبقةٌ موضوعيّةٌ واحدةٌ محسوبةٌ لا مُنتقاةٌ بالرأي.\n\n**البحث (/search).** بحثٌ دلاليٌّ (بالمعنى) ونصّيٌّ (باللفظ)، نتائجُه مرتّبةٌ بالجامعيّة فتَصعدُ الآياتُ الأصولُ إلى الصدارة.\n\n**نِبراس.** محادثةٌ بحثيّةٌ تسترجعُ من بياناتنا وتُؤلّفُ منها جوابًا، مؤصَّلةً على الآيات الأعلى جامعيّة؛ الذكاءُ يُؤلّفُ مادّةً محسوبةً ولا يتجاوزُها إلى تفسيرٍ من عنده.",
    "en_body": "From the measure and the vectors branch the following sections, each working in a known way:\n\n**Kulliyyāt (/kulliyat).** Every verse's classification: its tier, its theme, its index; and a \"Why this rank?\" panel that lays the six-factor arithmetic bare. Shown in muṣḥaf order or by jāmiʿiyya (the foundational first).\n\n**The mushaf map (/shabaka).** Every verse is a cell coloured by its computed tier — kulliyya, jāmiʿa, or tafṣīl — laid out in mushaf order by sūra; at a single glance you see where the foundational verses fall across the whole Qur'an: the skeleton of the book as the mīzān draws it.\n\n**Thematic threads (/khayt).** Tracing any concept across the muṣḥaf: we begin from a precise lexical grounding (the occurrences of the word and of its root) as a solid core, then add a tight semantic halo of the nearest verses, with a heat-strip of the thread's presence across the 114 sūras. (We favoured lexical grounding because semantic proximity alone is too loose for particular words.)\n\n**Topics (/mawdui).** The Qur'an's topics as computation yields them: ninety محاور that gather the verses by meaning-proximity to cover the whole muṣḥaf — each verse in exactly one — with each محور's verses ordered by jāmiʿiyya (the foundational first). One computed topic layer, not a picked index.\n\n**Search (/search).** Semantic (by meaning) and textual (by wording) search, its results ordered by jāmiʿiyya so the foundational verses rise to the top.\n\n**Nibrās.** A research chat that retrieves from our data and composes an answer from it, grounded on the highest-jāmiʿiyya verses; AI composes computed material and does not go past it into an interpretation of its own."
  },
  {
    "id": "other-tools",
    "ar_heading": "أدواتٌ أخرى في المشكاة",
    "en_heading": "Other instruments in Mishkāt",
    "ar_body": "وإلى جانب ما بُنِيَ على الميزان، أدواتٌ تخدمُ اللفظَ والمعنى:\n\n**فروق التنزيل.** نُحاذي آليًّا بين كلِّ آيتين متشابهتين لفظًا بخوارزمية محاذاة النصوص، فتظهرُ مواضعُ الاختلاف كلمةً كلمة: إبدالًا وتقديمًا وزيادةً وإيجازًا — نُبرِزُ الفرقَ، والقارئُ يتأمّلُه.\n\n**الفروق اللغويّة والمترادفات.** نُحوّلُ تعريفَ كلِّ جذرٍ في المعجمَين إلى متّجهِ معنًى، ثمّ نقيسُ القُربَ بينها: فأقربُها متّجهًا أقربُها معنًى (مترادفات)، وعناقيدُها المتبادلةُ حقولٌ دلاليّة.\n\n**الجذورُ والمعجمُ والصرف.** «المفردات» و«مقاييس اللغة» بين يديك، مع إحصاءٍ صرفيٍّ للقرآن كلِّه: نمرُّ على ١٣٠٬٠٣٠ مقطعًا في الوسم القرآنيّ (QAC) ونُحصي كلَّ سِمة — قسمَ الكلمة، ووزنَ الفعل وزمنَه، وحالتَه الإعرابيّة.\n\n**الأمثال.** أمثالُ القرآن مجموعةً منظومة.\n\n**أطلسُ الفواصل.** نظرةٌ في فواصل الآي وخواتيمِها.\n\nوكلُّ هذه البيانات محسوبةٌ قابلةٌ للفحص، تُنزَّلُ في ملفِّ Excel واحد.",
    "en_body": "Alongside what is built on the measure are instruments serving word and meaning:\n\n**Furūq al-tanzīl.** We align every pair of near-identical verses with a sequence-alignment algorithm, surfacing each difference word by word: substitution, reordering, addition and concision — we surface the difference; the reader contemplates it.\n\n**Lexical distinctions & synonyms.** We turn each root's lexicon definition into a meaning-vector, then measure closeness: nearest by vector is nearest by meaning (synonyms), and mutual clusters are semantic fields.\n\n**Roots, dictionary & morphology.** The *Mufradāt* and *Maqāyīs* at hand, with a morphology census of the whole Qur'an: we walk all 130,030 segments of the QAC morphology and tally every feature — word class, verb form and tense, grammatical case.\n\n**Parables.** The Qur'an's parables gathered and arranged.\n\n**Verse-ending atlas.** A look into the cadences and closings of the āyāt.\n\nAll of this data is computed and inspectable, downloadable in a single Excel file."
  },
  {
    "id": "closing",
    "ar_heading": "خاتمةٌ صادقة: بدايةُ الطريق",
    "en_heading": "An honest closing: the start of the road",
    "ar_body": "«مشكاة» مشروعٌ بحثيٌّ، لا مرجعٌ مُحكَم. حسبُنا أنّنا حسبنا من نصّ المصحف — بأدواتٍ معلومةٍ وحدودٍ صريحة — طبقةً من العلاقات والمعاني، وعرضناها في يُسرٍ ووضوح، إعانةً على النظر لا استبدالًا به.\n\nوما زلنا في بدايةِ الطريق في هذا الاتجاه: الميزانُ في مراجعة، وأوزانُه تُنقَّح، والأقسامُ تُثرى. والحسابُ — على انضباطه — مقاربةٌ قابلةٌ للتحسين.\n\nنُقدّمُ المحسوبَ مادّةً بين يدَي القارئ والباحث، ونرجو أن يكونَ عونًا في النظرِ والبحث.",
    "en_body": "Mishkāt is a research project, not a settled reference. Our claim is only that we have computed — from the muṣḥaf's text, with known tools and stated bounds — a layer of relations and meanings, and presented it plainly, to aid looking rather than to replace it.\n\nAnd we are still at the start of the road in this direction: the measure is under review, its weights are being refined, the sections are being enriched. Computation, for all its discipline, remains a human approach open to error and improvement.\n\nWe offer the computed as material in the hands of the reader and the researcher — we hope it serves reflection and study."
  }
];
